name: Reports

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # Build the reports
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Setup virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -e .
      
      - name: Build reports
        run: |
          which python
          python src/scripts/ballistics_reports.py
      
      - name: Setup pages
        uses: actions/configure-pages@v3
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build/"
      
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
